// <auto-generated />
namespace WebApplication2factor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class blankMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(blankMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202201130954217_blankMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
